/**
 * VisionAgent — Specialist agent for local image/OCR analysis.
 *
 * It keeps observed image/OCR evidence, local-model inferences, and integrity
 * verification separate so a missing OCR/VLM runtime cannot become fake data.
 */

import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { BaseAgent } from '../BaseAgent.js';
import { ComputerVisionService } from '../../services/vision/ComputerVisionService.js';

export class VisionAgent extends BaseAgent {
  constructor() {
    super('VisionAgent', 'All', 'Qwen2-VL-7B-Instruct');
  }

  static createReference(seed, prefix = 'TXT') {
    return `${prefix}-${crypto.createHash('sha256').update(String(seed)).digest('hex').slice(0, 16).toUpperCase()}`;
  }

  static decodeBase64Image(value) {
    const encoded = String(value || '')
      .replace(/^data:[^;]+;base64,/, '')
      .replace(/\s+/g, '');
    if (!encoded || !/^[A-Za-z0-9+/]*={0,2}$/.test(encoded)) return null;
    const buffer = Buffer.from(encoded, 'base64');
    return buffer.length ? buffer : null;
  }

  async plan() {
    return [
      '1. Verify the actual image signature, size, dimensions, and checksum locally',
      '2. Run OCR only through an available local OCR runtime',
      '3. Optionally call an explicitly configured private-LAN vision model',
      '4. Return observed evidence, AI inferences, and verification separately'
    ];
  }

  async execute(context) {
    const { query = '', imageText, imageBase64, fileName, inputContext = [] } = context;
    const safeFileName = ComputerVisionService.safeFilename(fileName || 'upload-image');
    let analysis = null;
    let sourceType = 'no_visual_input';
    let sourceText = '';
    const warnings = [];

    if (typeof imageText === 'string' && imageText.trim()) {
      sourceType = 'caller_supplied_text';
      sourceText = imageText.trim();
      warnings.push('Text was supplied by the caller; it was not generated by OCR for this request.');
    } else if (typeof imageBase64 === 'string' && imageBase64.trim()) {
      const bytes = VisionAgent.decodeBase64Image(imageBase64);
      if (!bytes) {
        sourceType = 'image_validation_failed';
        warnings.push('The image payload is not valid base64. No visual analysis was performed.');
      } else {
        const extension = path.extname(safeFileName) || '.bin';
        const temporaryPath = path.join(os.tmpdir(), `sovereign-vision-${crypto.randomUUID()}${extension}`);
        try {
          await fs.writeFile(temporaryPath, bytes);
          analysis = await ComputerVisionService.analyzeFile(temporaryPath, safeFileName, { query });
          if (analysis.success) {
            sourceType = analysis.ocr.text ? 'local_ocr' : 'image_metadata_only';
            sourceText = analysis.ocr.text || '';
            warnings.push(...(analysis.warnings || []));
          } else {
            sourceType = 'image_validation_failed';
            warnings.push(analysis.error?.message || 'The supplied image could not be analyzed locally.');
          }
        } finally {
          await fs.unlink(temporaryPath).catch(() => {});
        }
      }
    } else {
      for (const message of inputContext) {
        const result = message?.payload?.result;
        const upstreamText = result?.ocrResult?.textExtracted || result?.ocrResult?.extractedText || result?.answer || '';
        if (typeof upstreamText === 'string' && upstreamText.trim()) {
          sourceType = 'upstream_context';
          sourceText = upstreamText.trim();
          warnings.push('The text came from upstream context; this request did not perform a new image OCR pass.');
          break;
        }
      }
    }

    if (sourceType === 'no_visual_input') {
      warnings.push('No image or OCR text was supplied, so no visual observation was made from the query alone.');
    }

    const textEvidence = ['local_ocr', 'caller_supplied_text', 'upstream_context'].includes(sourceType) ? sourceText : '';
    const textHash = textEvidence ? crypto.createHash('sha256').update(textEvidence).digest('hex') : null;
    const referenceId = analysis?.verification?.sha256
      ? VisionAgent.createReference(analysis.verification.sha256, 'IMG')
      : textHash ? VisionAgent.createReference(textHash, 'TXT') : null;
    const detectedEntities = analysis?.entities?.length
      ? analysis.entities
      : ComputerVisionService.extractObservedEntities(textEvidence);
    const tableData = analysis?.tables?.length
      ? analysis.tables
      : ComputerVisionService.extractObservedTables(textEvidence);
    const confidenceScore = Number.isFinite(analysis?.ocr?.confidence) ? analysis.ocr.confidence : null;
    const observations = analysis?.observations || (textEvidence
      ? [{ label: 'Supplied text length', value: `${textEvidence.length} characters`, provenance: sourceType }]
      : []);
    const verification = analysis?.verification || (textHash
      ? { textSha256: textHash, provenance: 'calculated_from_supplied_text' }
      : {});
    const inferenceTextLength = (analysis?.inferences || []).reduce((total, item) => total + String(item?.value || '').length, 0);

    return {
      agent: this.name,
      query,
      ocrResult: {
        documentType: analysis?.image?.format
          ? `${analysis.image.format} image`
          : sourceType === 'no_visual_input' ? 'No image supplied' : 'Text-only input',
        sourceType,
        analysisStatus: analysis?.success
          ? 'COMPLETED'
          : sourceType === 'image_validation_failed' ? 'IMAGE_VALIDATION_FAILED' : 'NO_IMAGE_ANALYSIS',
        confidenceScore,
        confidence: confidenceScore === null ? 'UNAVAILABLE' : `${Math.round(confidenceScore * 1000) / 10}%`,
        referenceId,
        extractedText: textEvidence,
        textExtracted: textEvidence,
        detectedEntities,
        tableData,
        observations,
        inferences: analysis?.inferences || [],
        verification,
        capabilities: analysis?.capabilities || {
          ocr: { available: false, engine: 'not-run' },
          localVisionModel: { configured: false, ran: false, status: 'NOT_RUN' }
        },
        warnings
      },
      ocrEngine: analysis?.ocr?.engine || (sourceType === 'caller_supplied_text' ? 'caller-provided-text' : 'not-run'),
      ocrSimulation: analysis?.ocr?.isSimulated ?? false,
      tokensUsed: 60 + Math.ceil((textEvidence.length + inferenceTextLength) / 4)
    };
  }

  async validate(result) {
    const confidence = Number.isFinite(result.ocrResult?.confidenceScore) ? result.ocrResult.confidenceScore : 0;
    return {
      isValid: Boolean(result.ocrResult) && result.ocrResult.analysisStatus !== 'IMAGE_VALIDATION_FAILED',
      confidence,
      notes: result.ocrResult?.warnings?.[0] || 'Vision analysis completed without a confidence score from the local OCR engine.'
    };
  }
}
