/**
 * ReportTemplates — Structured report templates with executive summaries, metrics, and watermarks.
 */

export class ReportTemplates {
  static formatReport({
    templateType = 'executive', // 'executive' | 'audit' | 'data_science'
    title,
    department = 'Enterprise',
    findings = [],
    metrics = {},
    recommendations = [],
    citations = []
  }) {
    const watermark = 'CONFIDENTIAL — GENERATED BY SOVEREIGN AI ON-PREMISE WORKBENCH';
    const timestamp = new Date().toISOString();

    const sections = [];

    // Header section
    sections.push({
      heading: '1. Executive Briefing',
      content: `This report compiles the supplied findings and citations for ${department}. Conclusions are limited to the evidence shown below; a local model narrative is included only when a live local model completed it.`
    });

    // Key findings section
    sections.push({
      heading: '2. Core Analytical Findings',
      content: findings.length > 0 
        ? findings.map((f, i) => `${i + 1}. ${f}`).join('\n')
        : 'No source evidence was supplied. No operational or compliance conclusion has been generated.'
    });

    // Quantitative metrics section
    if (Object.keys(metrics).length > 0) {
      sections.push({
        heading: '3. Quantitative Telemetry & Key Indicators',
        content: Object.entries(metrics).map(([k, v]) => `• ${k}: ${typeof v === 'object' ? JSON.stringify(v) : v}`).join('\n')
      });
    }

    // Recommendations section
    sections.push({
      heading: '4. Strategic Recommendations',
      content: recommendations.length > 0
        ? recommendations.map((r, i) => `• Recommendation ${i + 1}: ${r}`).join('\n')
        : '• No recommendation has been generated without supporting evidence.'
    });

    // Source citations section
    if (citations.length > 0) {
      sections.push({
        heading: '5. Verified Evidentiary Citations',
        content: citations.map((c, i) => `[Source ${i + 1}] ${c.documentTitle || c.title} (${c.department || department}) — ${c.sectionTitle || c.category || 'Reference'}`).join('\n')
      });
    }

    const markdownText = `# ${title.toUpperCase()}\n\n` +
      `> **Classification**: TOP SECRET // RESTRICTED DEPT DISTRIBUTION\n` +
      `> **Watermark**: ${watermark}\n` +
      `> **Generated**: ${timestamp}\n\n` +
      sections.map(s => `## ${s.heading}\n\n${s.content}\n\n`).join('---\n\n') +
      `\n*Report integrity metadata recorded. Verify conclusions against the cited sources and local-model runtime status.*`;

    return {
      title,
      templateType,
      department,
      watermark,
      generatedAt: timestamp,
      sections,
      markdown: markdownText
    };
  }
}
